name: Ping Web Site

on:
  push:
    branches: [ master ]
  schedule: 
    - cron: '*/10 * * * *' #every 10 minutes
jobs:
  ping:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet tool install Web.Ping -g
    - name: Ping ggzy.zhenjiang.gov.cn
      run: Web.Ping --host http://ggzy.zhenjiang.gov.cn/
    - name: Ping ggzy.zhenjiang.gov.cn
      run: Web.Ping --host http://ggzy.zhenjiang.gov.cn/
